# Ce sont des plateformes de modèles de financement pris en charge

github: [Steve Aster Afovo]
community_bridge: Open source Community

lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom : ["https://direct.kkiapay.me/3343/parrainage-gitub"]
